### ISSUE TITLE
Initial Django Setup

### ISSUE THREAD

**Issue by Lorenz-127** [Lorenz-127/Developers-Journal#2]
### Acceptance Criteria

- AC1: Project started and ready for first App

### Tasks

- [ ] Create Gitpod Workspace
- [ ] Start Django project
- [ ] Install initial dependencies
- [ ] Add environment variables
